### ISSUE TITLE
Virtual Branch with TOML codeblock

### ISSUE THREAD

**Issue by aaomidi** [aaomidi/virtual-branches-ground-zero#3]
```toml
Target = "test3"
Base = "main"
Track = [
  "A",
  "B"
]
```
